name: xcodebuild

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: mxcl/xcodebuild@v1
        with:
          xcode: 12
          platform: macOS
          action: build
          configuration: release
          code-sign-identity: '-'
