name: xcodebuild

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: curl -o swift-bundler -L https://github.com/stackotter/swift-bundler/releases/download/v1.0.0/swift-bundler |
             chmod +x ./swift-bundler |
             sh ./Setup.sh
             ./swift-bundler build -c release -o .
