name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout delta-client
        uses: actions/checkout@v2
      - name: Download swift-bundler
        run: |
          curl -o swift-bundler -L https://github.com/stackotter/swift-bundler/releases/download/v1.1.0/swift-bundler
          chmod +x ./swift-bundler
      - name: Build
        run: ./swift-bundler build -c release -o . -u
      - name: Zip .app
        run: zip -r DeltaClient.zip DeltaClient.app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Delta Client
          path: ./DeltaClient.app
             
